Upgrade to mach core 2.0
privacyidea/simplesamlphp-module-privacyidea pull request #209
Opened 2024-04-22 11:11 UTC by lukasmatusiewicz

2024-04-29 11:21 UTC, nilsbehlen requested changes

2024-04-29 11:56 UTC, lukasmatusiewicz commented on composer.json
> +    "description": "Add Multi-Factor Authentication to simpleSAMLphp. The MFA is managed in privacyIDEA.",
second factors

2024-04-29 11:57 UTC, nilsbehlen commented on composer.json
> +    "description": "Add Multi-Factor Authentication to simpleSAMLphp. The MFA is managed in privacyIDEA.",
Add multi-factor authentication to simpleSAMLphp. The secind factors are managed in privacyIDEA.

2024-04-30 10:02 UTC, lukasmatusiewicz commented on composer.json
> +    "description": "Add Multi-Factor Authentication to simpleSAMLphp. The MFA is managed in privacyIDEA.",
[8b8eda4](https://github.com/privacyidea/simplesamlphp-module-privacyidea/pull/209/commits/8b8eda4f9bd3a17e0113f0f4bd19339a07575d06)

2024-04-30 10:06 UTC, lukasmatusiewicz commented on README.md
> +so `SimpleSAML\Logger::DEBUG`. Alternatively,
[079ae04](https://github.com/privacyidea/simplesamlphp-module-privacyidea/pull/209/commits/079ae0476e07d1bd8fe66b3af40c3218b46cfcc6)

2024-04-30 10:10 UTC, lukasmatusiewicz commented on src/Auth/Process/PrivacyideaAuthProc.php
> +    /* @var PrivacyIDEA|null This is an object from privacyIDEA class */
[f6d2133](https://github.com/privacyidea/simplesamlphp-module-privacyidea/pull/209/commits/f6d213399ebf0dee7c26a081461f70f703359a13)

2024-04-30 10:10 UTC, lukasmatusiewicz commented on src/Auth/PrivacyIDEA.php
> +
[f6d2133](https://github.com/privacyidea/simplesamlphp-module-privacyidea/pull/209/commits/f6d213399ebf0dee7c26a081461f70f703359a13)

2024-04-30 10:10 UTC, lukasmatusiewicz commented on public/FormBuilder.php
> +    //$tpl = new Template(Configuration::getInstance(), 'privacyidea:LoginForm.php');
[f6d2133](https://github.com/privacyidea/simplesamlphp-module-privacyidea/pull/209/commits/f6d213399ebf0dee7c26a081461f70f703359a13)

2024-04-30 10:11 UTC, lukasmatusiewicz commented on README.md
> +This module adds flexible, enterprise grade Multi-Factor Authentication
[f6d2133](https://github.com/privacyidea/simplesamlphp-module-privacyidea/pull/209/commits/f6d213399ebf0dee7c26a081461f70f703359a13)

2024-05-06 11:14 UTC, nilsbehlen approved these changes

2024-05-06 11:14 UTC, merged